# Generated by Django 4.2 on 2023-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_time_online', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=20)),
                ('amount_of_tags', models.CharField(max_length=50)),
                ('number_of_chats_per_entry', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
